# Configuration for resolvconf(8)
# See resolvconf.conf(5) for details

# Use local nameserver
name_servers="::1 127.0.0.1"
resolv_conf_options="trust-ad"

# Mirror the Debian package defaults for the below resolvers
# so that resolvconf integrates seemlessly.
dnsmasq_resolv=/var/run/dnsmasq/dnsmasq-resolv.conf
pdnsd_conf=/etc/pdnsd.conf
unbound_conf=/etc/unbound/unbound.conf.d/resolvconf_resolvers.conf
