# Define the number of worker processes to handle requests
worker_processes 5;

events {
    # Set the maximum number of simultaneous connections that can be handled by each worker process
    worker_connections  16;
}

http {
    # Include MIME type definitions from the specified file
    include       /etc/nginx/mime.types;

    # Default content-type if not specified in response headers
    default_type  application/octet-stream;

    # Define a log format named 'main' to be used for access logs
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # Specify the location and format of the access log file
    access_log  /var/log/nginx/access.log  main;

    # Enable sendfile for more efficient file transfers
    sendfile        on;

    # Optional directive to improve performance by avoiding small TCP packets (commented out)
    #tcp_nopush     on;

    # Set the timeout for keep-alive connections
    keepalive_timeout  65;

    # Enable gzip compression for certain types of responses
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Include additional configuration files from the specified directory
    include /etc/nginx/conf.d/*.conf;
}